"""criar vinculos e jornadas

Revision ID: f0ade2a850e3
Revises: 027230aa4afa
Create Date: 2026-09-27 16:55:12.244356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ade2a850e3'
down_revision: Union[str, Sequence[str], None] = '027230aa4afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica a migração."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jornadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('passo_atual', sa.Enum('consulta', 'exame', 'retorno', name='passo_jornada'), nullable=False),
    sa.Column('status', sa.Enum('ativa', 'encerrada', name='status_jornada'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paciente_id')
    )
    op.create_index(op.f('ix_jornadas_medico_id'), 'jornadas', ['medico_id'], unique=False)
    op.create_table('vinculos_medico_paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paciente_id')
    )
    op.create_index(op.f('ix_vinculos_medico_paciente_medico_id'), 'vinculos_medico_paciente', ['medico_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Desfaz a migração."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vinculos_medico_paciente_medico_id'), table_name='vinculos_medico_paciente')
    op.drop_table('vinculos_medico_paciente')
    op.drop_index(op.f('ix_jornadas_medico_id'), table_name='jornadas')
    op.drop_table('jornadas')
    # ### end Alembic commands ###
