"""criar consultas solicitacoes exames arquivos e mensagens

Revision ID: 8e44718c7b29
Revises: f0ade2a850e3
Create Date: 2026-09-27 17:16:19.113012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e44718c7b29'
down_revision: Union[str, Sequence[str], None] = 'f0ade2a850e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica a migração."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('nome_armazenado', sa.String(length=64), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=False),
    sa.Column('enviado_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_armazenado')
    )
    op.create_index(op.f('ix_arquivos_jornada_id'), 'arquivos', ['jornada_id'], unique=False)
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('consulta', 'retorno', name='tipo_consulta'), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('anotacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_jornada_id'), 'consultas', ['jornada_id'], unique=False)
    op.create_table('solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('exame', 'consulta_extra', 'orientacao_profissional', 'outro', name='tipo_solicitacao'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('prazo', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'atendida', 'cancelada', name='status_solicitacao'), nullable=False),
    sa.Column('atendida_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacoes_jornada_id'), 'solicitacoes', ['jornada_id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_prazo'), 'solicitacoes', ['prazo'], unique=False)
    op.create_table('exames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=True),
    sa.Column('enviado_por_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('arquivo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('enviado', 'revisado', name='status_exame'), nullable=False),
    sa.Column('observacao_revisao', sa.Text(), nullable=True),
    sa.Column('revisado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivos.id'], ),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exames_jornada_id'), 'exames', ['jornada_id'], unique=False)
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('remetente_id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('arquivo_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivos.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_criado_em'), 'mensagens', ['criado_em'], unique=False)
    op.create_index(op.f('ix_mensagens_jornada_id'), 'mensagens', ['jornada_id'], unique=False)
    op.create_table('prescricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('dosagem', sa.String(length=120), nullable=True),
    sa.Column('instrucoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescricoes_consulta_id'), 'prescricoes', ['consulta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Desfaz a migração."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescricoes_consulta_id'), table_name='prescricoes')
    op.drop_table('prescricoes')
    op.drop_index(op.f('ix_mensagens_jornada_id'), table_name='mensagens')
    op.drop_index(op.f('ix_mensagens_criado_em'), table_name='mensagens')
    op.drop_table('mensagens')
    op.drop_index(op.f('ix_exames_jornada_id'), table_name='exames')
    op.drop_table('exames')
    op.drop_index(op.f('ix_solicitacoes_prazo'), table_name='solicitacoes')
    op.drop_index(op.f('ix_solicitacoes_jornada_id'), table_name='solicitacoes')
    op.drop_table('solicitacoes')
    op.drop_index(op.f('ix_consultas_jornada_id'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_arquivos_jornada_id'), table_name='arquivos')
    op.drop_table('arquivos')
    # ### end Alembic commands ###
