"""ficha do paciente e parceiros da jornada

Revision ID: 31fff3580a16
Revises: 715e13c941c6
Create Date: 2026-10-07 15:23:38.828775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31fff3580a16'
down_revision: Union[str, Sequence[str], None] = '715e13c941c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica a migração."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fichas_paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('masculino', 'feminino', 'outro', name='sexo'), nullable=True),
    sa.Column('altura_cm', sa.Integer(), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('diagnosticos', sa.Text(), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('medicamentos_em_uso', sa.Text(), nullable=True),
    sa.Column('restricoes', sa.Text(), nullable=True),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paciente_id')
    )
    op.create_table('jornada_parceiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('parceiro_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.ForeignKeyConstraint(['parceiro_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jornada_id', 'parceiro_id', name='uq_jornada_parceiros_jornada_parceiro')
    )
    op.create_index(op.f('ix_jornada_parceiros_jornada_id'), 'jornada_parceiros', ['jornada_id'], unique=False)
    op.create_index(op.f('ix_jornada_parceiros_parceiro_id'), 'jornada_parceiros', ['parceiro_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Desfaz a migração."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jornada_parceiros_parceiro_id'), table_name='jornada_parceiros')
    op.drop_index(op.f('ix_jornada_parceiros_jornada_id'), table_name='jornada_parceiros')
    op.drop_table('jornada_parceiros')
    op.drop_table('fichas_paciente')
    # ### end Alembic commands ###
