"""modelo inicial

Revision ID: 715e13c941c6
Revises: 
Create Date: 2026-10-07 15:02:17.816028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '715e13c941c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica a migração."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('medico', 'paciente', 'parceiro', name='tipo_usuario'), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('profissao', sa.String(length=100), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=True),
    sa.Column('senha_provisoria_hash', sa.String(length=255), nullable=True),
    sa.Column('senha_provisoria_expira_em', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('deve_trocar_senha', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_login_em', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('criado_em', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.CheckConstraint("tipo_usuario = 'paciente' OR profissao IS NOT NULL", name='ck_usuarios_profissao_obrigatoria'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('jornadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('passo_atual', sa.Enum('consulta', 'exame', 'retorno', name='passo_jornada'), nullable=False),
    sa.Column('status', sa.Enum('ativa', 'encerrada', name='status_jornada'), nullable=False),
    sa.Column('criado_em', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paciente_id')
    )
    op.create_index(op.f('ix_jornadas_medico_id'), 'jornadas', ['medico_id'], unique=False)
    op.create_table('arquivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('nome_armazenado', sa.String(length=64), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=False),
    sa.Column('enviado_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_armazenado')
    )
    op.create_index(op.f('ix_arquivos_jornada_id'), 'arquivos', ['jornada_id'], unique=False)
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('consulta', 'retorno', name='tipo_consulta'), nullable=False),
    sa.Column('data', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('anotacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_jornada_id'), 'consultas', ['jornada_id'], unique=False)
    op.create_table('solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('exame', 'consulta_extra', 'orientacao_profissional', 'outro', name='tipo_solicitacao'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('prazo', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'atendida', 'cancelada', name='status_solicitacao'), nullable=False),
    sa.Column('atendida_em', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('criado_em', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacoes_jornada_id'), 'solicitacoes', ['jornada_id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_prazo'), 'solicitacoes', ['prazo'], unique=False)
    op.create_table('exames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=True),
    sa.Column('enviado_por_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('arquivo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('enviado', 'revisado', name='status_exame'), nullable=False),
    sa.Column('observacao_revisao', sa.Text(), nullable=True),
    sa.Column('revisado_em', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('criado_em', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivos.id'], ),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exames_jornada_id'), 'exames', ['jornada_id'], unique=False)
    op.create_table('prescricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('dosagem', sa.String(length=120), nullable=True),
    sa.Column('instrucoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescricoes_consulta_id'), 'prescricoes', ['consulta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Desfaz a migração."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescricoes_consulta_id'), table_name='prescricoes')
    op.drop_table('prescricoes')
    op.drop_index(op.f('ix_exames_jornada_id'), table_name='exames')
    op.drop_table('exames')
    op.drop_index(op.f('ix_solicitacoes_prazo'), table_name='solicitacoes')
    op.drop_index(op.f('ix_solicitacoes_jornada_id'), table_name='solicitacoes')
    op.drop_table('solicitacoes')
    op.drop_index(op.f('ix_consultas_jornada_id'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_arquivos_jornada_id'), table_name='arquivos')
    op.drop_table('arquivos')
    op.drop_index(op.f('ix_jornadas_medico_id'), table_name='jornadas')
    op.drop_table('jornadas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
